### ISSUE TITLE
class 'WPEL Activation' not found with new update

### ISSUE THREAD

**Issue by FranStoker** [freelancephp/WP-External-Links#17]
Hi 

Today you have released an update, but when I do, the error class 'WPEL Activation' not found is thrown, so I had to downgrade.

Thanks

**Comment by freelancephp** [comment]
Hello Fran,

Something went wrong on commiting the code. When I updated on my test-installations it went well. So that's strange.

But now it should work.
[https://wordpress.org/support/topic/wpel_activation-fatal-error/](https://wordpress.org/support/topic/wpel_activation-fatal-error/)

Regards,
Victor

**Comment by FranStoker** [comment]
Yeah, i seems it works fine now :)

Thanks and, by the way, great plugin!

**Comment by freelancephp** [comment]
Great.
And thanks!
